#!/bin/bash

# Written by Rodrigo Esteves baitsart@gmail.com www.youtube.com/user/baitsart 
# GNU License. You are free to modify and redistribute   # 

key="AIzaSyBOti4mM-6x9WDnZIjIeyEU21OpBXqWBgw"

if [ -z "$1" ]; then
/bin/bash ~/.voice_commands/play_stop.sh
exit
fi
if echo "$@" | awk '{print $1, $2}' | grep -- "-t\|-try" | sed 's/-try//g;s/-t//' | awk '{print $1}' | grep -x -q -- "-l\|-lang"; then

lang=$(echo "$@" | sed 's/-try//g;s/-t//g;s/-lang//g;s/-l//' | sed 's/^[ ]*//' | awk '{print $1}')
echo "(af africano), (ar árabe), (az azerbaiyán), (be bielorruso), (bg búlgaro), (bn bengalí), (ca catalán), (cs checo), (cy galés), (da danés), (de alemán), (el griego), (en inglés), (eo esperanto), (es español), (et estonia), (eu vasco), (fa persa), (fi finlandés), (fr francés), (ga irlandés), (gl gallego), (gu gujarati), (hi hindi), (hr croata), (ht haitiano), (hu húngaro), (hy armenio), (id indonesio), (is islandés), (it italiano), (iw hebreo), (ja japonés), (ka georgiano), (km khmer), (kn canarés), (ko coreano), (la latino), (lo lao), (lt lituano), (lv letón), (mk macedonio), (ms malayo), (mt maltés), (nl holandés), (no noruego), (pl polaco), (pt portugués), (ro rumano), (ru ruso), (sk eslovaco), (sl esloveno), (sq albanés), (sr serbio), (sv sueco), (sw medio), (ta tamil), (te telugu), (th tailandés), (tl filipino), (tr turco), (uk ucranio), (ur urdu), (vi vietnamita), (yi yídish), (zh-CN chino)" > /tmp/lang 
language_list=$(cat /tmp/lang)

if echo "$language_list" | sed 's/), (/\n/g;s/(//g;s/)//g' | cut -d' ' -f2 | grep -x -q -i "$lang"; then
	language=$( echo "$language_list" | sed 's/), (/\n/g;s/(//g;s/)//g'  | grep "$lang" | awk '{print $1}')
commands=$(echo "$@" | sed 's/-try//g;s/-t//g;s/-lang//g;s/-l//g;s/'"$lang"'//' | sed 's/^[ ]*//' )
CMD_RETRY=$(sed -n '95p' ~/.voice_commands/"v-c LANGS"/commands-"$language")
if echo "$commands" | grep -q "$CMD_RETRY" ; then
[[ -f /tmp/speech_recognition_prev.tmp ]] || notify-send "No hay un comando anterior" "Ejecutar de nuevo, por favor"
mv /tmp/speech_recognition_prev.tmp /tmp/speech_recognition.tmp
/bin/bash ~/.voice_commands/speech_commands.sh "$language" "$key"
exit 1
fi
echo "$commands" > /tmp/speech_recognition.tmp
/bin/bash ~/.voice_commands/speech_commands.sh "$language" "$key"
exit 1
fi
if echo "$language_list" | sed 's/), (/\n/g;s/(//g;s/)//g' | cut -d' ' -f1 | grep -x -q -i "$lang"; then
	language=$( echo "$language_list" | sed 's/), (/\n/g;s/(//g;s/)//g'  | grep -i "$lang " | awk '{print $1}')
commands=$(echo "$@" | sed 's/-try//g;s/-t//g;s/-lang//g;s/-l//g;s/'"$lang"'//' | sed 's/^[ ]*//' )
CMD_RETRY=$(sed -n '95p' ~/.voice_commands/"v-c LANGS"/commands-"$language")
if echo "$commands" | grep -q "$CMD_RETRY" ; then
[[ -f /tmp/speech_recognition_prev.tmp ]] || notify-send "No hay un comando anterior" "Ejecutar de nuevo, por favor"
mv /tmp/speech_recognition_prev.tmp /tmp/speech_recognition.tmp
/bin/bash ~/.voice_commands/speech_commands.sh "$language" "$key"
exit 1
fi
echo "$commands" > /tmp/speech_recognition.tmp
/bin/bash ~/.voice_commands/speech_commands.sh "$language" "$key"
exit 1
fi
echo "No hay opción lang: $lang
Lista de idiomas disponibles es:
 (Abreviatura idioma, o idioma nombre completo)

`echo "$language_list"`"
exit 0;
fi
if echo "$1" | grep -x -q -- "-t\|-try"; then
commands=$(echo "$@" | sed 's/-try//g;s/-t//' | sed 's/^[ ]*//')
language="es"
CMD_RETRY=$(sed -n '95p' ~/.voice_commands/"v-c LANGS"/commands-"$language")
if echo "$commands" | grep -q "$CMD_RETRY" ; then
[[ -f /tmp/speech_recognition_prev.tmp ]] || notify-send "No hay un comando anterior" "Ejecutar de nuevo, por favor"
mv /tmp/speech_recognition_prev.tmp /tmp/speech_recognition.tmp
/bin/bash ~/.voice_commands/speech_commands.sh "$language" "$key"
exit 1
fi
echo "$commands" > /tmp/speech_recognition.tmp
/bin/bash ~/.voice_commands/speech_commands.sh "$language" "$key"
exit 1
fi
if echo "$1" | grep -x -q -- "-l\|-lang"; then
language=$(echo "$@" | sed 's/-lang//g;s/-l//' | awk '{print $1}')
echo "(af africano), (ar árabe), (az azerbaiyán), (be bielorruso), (bg búlgaro), (bn bengalí), (ca catalán), (cs checo), (cy galés), (da danés), (de alemán), (el griego), (en inglés), (eo esperanto), (es español), (et estonia), (eu vasco), (fa persa), (fi finlandés), (fr francés), (ga irlandés), (gl gallego), (gu gujarati), (hi hindi), (hr croata), (ht haitiano), (hu húngaro), (hy armenio), (id indonesio), (is islandés), (it italiano), (iw hebreo), (ja japonés), (ka georgiano), (km khmer), (kn canarés), (ko coreano), (la latino), (lo lao), (lt lituano), (lv letón), (mk macedonio), (ms malayo), (mt maltés), (nl holandés), (no noruego), (pl polaco), (pt portugués), (ro rumano), (ru ruso), (sk eslovaco), (sl esloveno), (sq albanés), (sr serbio), (sv sueco), (sw medio), (ta tamil), (te telugu), (th tailandés), (tl filipino), (tr turco), (uk ucranio), (ur urdu), (vi vietnamita), (yi yídish), (zh-CN chino)" > /tmp/lang 
language_list=$(cat /tmp/lang)

if echo "$language_list" | sed 's/), (/\n/g;s/(//g;s/)//g' | cut -d' ' -f2 | grep -x -q -i "$language"; then
	language=$( echo "$language_list" | sed 's/), (/\n/g;s/(//g;s/)//g'  | grep -i -o "$language" | awk '{print $1}')
/bin/bash ~/.voice_commands/play_stop.sh "$language"
exit
fi
if echo "$language_list" | sed 's/), (/\n/g;s/(//g;s/)//g' | cut -d' ' -f1 | grep -x -q -i "$language"; then
	language=$( echo "$language_list" | sed 's/), (/\n/g;s/(//g;s/)//g'  | grep -i -o "$language" | awk '{print $1}')
/bin/bash ~/.voice_commands/play_stop.sh "$language"
exit
fi
echo "No hay opción lang: $language
Lista de idiomas disponibles es:
 (Abreviatura idioma, o idioma nombre completo)

`echo "$language_list"`"
exit 0;
fi
if echo "$1" | grep -x -q -i -- "-r"; then
/bin/bash ~/.voice_commands/play_stop.sh
exit
fi
if echo "$@" | awk '{print $1, $2}' | grep -- "-m\|-mod" | sed 's/-mod//g;s/-m//' | awk '{print $1}' | grep -x -q -- "-l\|-lang"; then

lang=$(echo "$@" | sed 's/-mod//g;s/-m//g;s/-lang//g;s/-l//' | sed 's/^[ ]*//' | awk '{print $1}')
echo "(af africano), (ar árabe), (az azerbaiyán), (be bielorruso), (bg búlgaro), (bn bengalí), (ca catalán), (cs checo), (cy galés), (da danés), (de alemán), (el griego), (en inglés), (eo esperanto), (es español), (et estonia), (eu vasco), (fa persa), (fi finlandés), (fr francés), (ga irlandés), (gl gallego), (gu gujarati), (hi hindi), (hr croata), (ht haitiano), (hu húngaro), (hy armenio), (id indonesio), (is islandés), (it italiano), (iw hebreo), (ja japonés), (ka georgiano), (km khmer), (kn canarés), (ko coreano), (la latino), (lo lao), (lt lituano), (lv letón), (mk macedonio), (ms malayo), (mt maltés), (nl holandés), (no noruego), (pl polaco), (pt portugués), (ro rumano), (ru ruso), (sk eslovaco), (sl esloveno), (sq albanés), (sr serbio), (sv sueco), (sw medio), (ta tamil), (te telugu), (th tailandés), (tl filipino), (tr turco), (uk ucranio), (ur urdu), (vi vietnamita), (yi yídish), (zh-CN chino)" > /tmp/lang 
language_list=$(cat /tmp/lang)

if echo "$language_list" | sed 's/), (/\n/g;s/(//g;s/)//g' | cut -d' ' -f2 | grep -x -q -i "$lang"; then
	language=$( echo "$language_list" | sed 's/), (/\n/g;s/(//g;s/)//g'  | grep "$lang" | awk '{print $1}')
gedit ~/.voice_commands/README.md ~/.voice_commands/"v-c LANGS"/commands-"$language"
exit 1
fi
if echo "$language_list" | sed 's/), (/\n/g;s/(//g;s/)//g' | cut -d' ' -f1 | grep -x -q -i "$lang"; then
	language=$( echo "$language_list" | sed 's/), (/\n/g;s/(//g;s/)//g'  | grep -i "$lang " | awk '{print $1}')
gedit ~/.voice_commands/README.md ~/.voice_commands/"v-c LANGS"/commands-"$language"
exit 1
fi
echo "No hay opción lang: $lang
Lista de idiomas disponibles es:
 (Abreviatura idioma, o idioma nombre completo)

`echo "$language_list"`"
exit 0;
fi
if echo "$1" | grep -x -q -i -- "-m\|-mod"; then
language="es"
gedit ~/.voice_commands/README.md ~/.voice_commands/"v-c LANGS"/commands-"$language"
exit
fi
if echo "$1" | grep -x -q -i -- "-h"; then
cat ~/.voice_commands/README.md
exit
fi
if echo "$1" | grep -x -q -i -- "-v"; then
echo "# Comandos de Voz (comanda tu PC con órdenes habladas) #
Versión 1.0.0-4"
exit
fi
if echo "$1" | grep -x -q -i -- "--help"; then
echo "
	# Comandos de Voz (comanda tu PC con órdenes habladas) #
Versión 1.0.0-4
	v-c , command line options

v-c -r		Correr
v-c -l -lang	Para seleccionar otro, de 67 idiomas de reconocimiento .
v-c -t -try	Para tratar cualquier comando, de manera predeterminada lang, o un [-lang].
v-c -m -mod	Para modificar el archivo de comandos y el archivo README.
v-c -h		Documento Ver instrucciones README.
v-c --help	Mostrar este mensaje"
exit
fi
echo "No hay un comando $1
Intentar v-c --help, Para ver los comandos disponibles"

